# Generated by Django 5.0.3 on 2024-04-10 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='图书名')),
                ('publish', models.CharField(max_length=64, null=True, verbose_name='出版社')),
                ('autor', models.CharField(max_length=64, null=True, verbose_name='作者')),
                ('isbn', models.CharField(max_length=32, null=True, verbose_name='ISBN')),
                ('tagname', models.CharField(max_length=32, null=True, verbose_name='标签')),
                ('year', models.DateField(max_length=32, null=True, verbose_name='出版日期')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='评分')),
                ('booklogo', models.ImageField(null=True, upload_to='bookimage/', verbose_name='图片封面')),
                ('desc', models.TextField(null=True, verbose_name='介绍')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户姓名')),
                ('mobile_phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('avator', models.ImageField(null=True, upload_to='avatars/', verbose_name='用户头像')),
            ],
        ),
        migrations.CreateModel(
            name='DoubanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='评论')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='评论人')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='评分')),
                ('create_date', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo', verbose_name='评论图书')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='评论')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='评分')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo', verbose_name='评论图书')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.userinfo', verbose_name='评论人')),
            ],
        ),
        migrations.CreateModel(
            name='BookVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2, null=True, verbose_name='评分')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo', verbose_name='点评图书')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.userinfo', verbose_name='点赞人')),
            ],
        ),
    ]
