# Generated by Django 5.0.3 on 2024-04-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_doubanreview_namelogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookvote',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='doubanreview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='bookvote',
            name='star',
            field=models.IntegerField(null=True, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='doubanreview',
            name='star',
            field=models.IntegerField(null=True, verbose_name='评分'),
        ),
    ]
