# Generated by Django 5.0.3 on 2024-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_bookvote_rating_remove_doubanreview_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanreview',
            name='namelogo',
            field=models.CharField(blank=True, max_length=520, null=True, verbose_name='评论人头像'),
        ),
    ]
