# Generated by Django 5.0.3 on 2024-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_bookinfo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='year',
            field=models.CharField(max_length=32, null=True, verbose_name='出版日期'),
        ),
    ]
