# Generated by Django 5.0.3 on 2024-04-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_bookinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='name',
            field=models.CharField(blank=True, max_length=1255, null=True, verbose_name='图书名'),
        ),
    ]
