# Generated by Django 5.0.3 on 2024-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubanreview',
            name='name',
            field=models.CharField(blank=True, max_length=1255, null=True, verbose_name='评论人'),
        ),
    ]
