# Generated by Django 5.0.3 on 2024-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_review_star_delete_bookvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='create_datetime',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
