# Generated by Django 5.0.3 on 2024-04-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_bookinfo_create_datetime_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktype', models.IntegerField(choices=[(1, '热门图书'), (2, '新上书籍'), (3, '高分书籍')], verbose_name='书籍类型')),
                ('book', models.ManyToManyField(to='book.bookinfo')),
            ],
        ),
    ]
