# Generated by Django 5.0.3 on 2024-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_remove_booktype_book_bookinfo_booktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户姓名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
